/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "thalwvebdagictyzuvbj"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoYWx3dmViZGFnaWN0eXp1dmJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3OTI2MTAsImV4cCI6MjA4NjM2ODYxMH0.4ygF7on7UfADrEILwO7-TV-4YunuUjOyCA2b8ra-UgU"